receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1024
    timeout: 1s
  
  memory_limiter:
    limit_mib: 512
  
  resource:
    attributes:
      - key: service.instance.id
        from_attribute: service.instance.id
        action: upsert
      - key: service.version
        from_attribute: service.version
        action: upsert

exporters:
  # Export metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      collector: "otel-collector"
    
  # Export logs to Loki
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tenant_id: "grafana"
    
  # Export traces to Tempo
  otlp/tempo:
    endpoint: tempo:9095
    tls:
      insecure: true

  # Debug logging
  logging:
    loglevel: info

service:
  telemetry:
    logs:
      level: info
      encoding: json
    metrics:
      address: 0.0.0.0:8888

  pipelines:
    # Traces pipeline - send to Tempo
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/tempo, logging]
    
    # Metrics pipeline - send to Prometheus  
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, logging]
    
    # Logs pipeline - send to Loki
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki, logging]

  extensions: []
